export const ADD_COUNTER = 'add_counter'
export const ADD_TO_CART = 'add_to_cart'
export const CHECK_TOGGLE = 'check_toggle'
export const ALL_NOT_SELECT ='all_not_select'
export const SELECT_ALL = 'select_all'